### PR TITLE
CMake: install libsae.so as well

### PR DESCRIPTION
**Pull request by yegorich**
Signed-off-by: Yegor Yefremov <yegorslists@googlemail.com>

### CODE REVIEW

**Comment by bcopeland** [comment]
This looks fine, but out of curiosity, what are you using libsae.so for?  meshd is statically linked.

**Comment by yegorich** [comment]
In Buildroot meshd-nl80211 was linked dynamically and it was missing libsae.so

**Comment by bcopeland** [comment]
Hmm, ok.  Wonder what is different about buildroot?  
```
$ ldd meshd-nl80211 
	linux-vdso.so.1 (0x00007ffdcd3ab000)
	libconfig.so.9 => /usr/lib/x86_64-linux-gnu/libconfig.so.9 (0x00007f9c114ca000)
	libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f9c110ce000)
	libnl-3.so.200 => /usr/local/lib/libnl-3.so.200 (0x00007f9c10eb4000)
	libnl-genl-3.so.200 => /usr/local/lib/libnl-genl-3.so.200 (0x00007f9c10caf000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9c10aa7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9c106fb000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9c104f7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9c102da000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9c0ffd8000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a976db7000)
```

I don't know anything about CMake but should ```ADD_LIBRARY(sae)``` be ```ADD_LIBRARY(sae STATIC)``` to force the issue?

**Comment by yegorich** [comment]
I have different output:

LD_TRACE_LOADED_OBJECTS=1 /usr/bin/meshd-nl80211
        linux-vdso.so.1 (0xbef1a000)
        libconfig.so.9 => /usr/lib/libconfig.so.9 (0xb6f46000)
        libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0xb6de5000)
        libnl-3.so.200 => /usr/lib/libnl-3.so.200 (0xb6dbe000)
        libnl-genl-3.so.200 => /usr/lib/libnl-genl-3.so.200 (0xb6daa000)
        libsae.so => /usr/lib/libsae.so (0xb6d8b000)
        librt.so.1 => /lib/librt.so.1 (0xb6d75000)
        libc.so.6 => /lib/libc.so.6 (0xb6c88000)
        libdl.so.2 => /lib/libdl.so.2 (0xb6c75000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xb6c61000)
        libm.so.6 => /lib/libm.so.6 (0xb6bec000)
        /lib/ld-linux-armhf.so.3 (0xb6f5f000)

**Comment by bcopeland** [comment]
does putting STATIC after sae in the `ADD_LIBRARY(sae ${libsae_sources})` stanza fix it for buildroot?

**Comment by yegorich** [comment]
Yes, it does.

**Comment by bcopeland** [comment]
OK, care to send a PR for that change instead?

**Comment by yegorich** [comment]
Will do.

**Comment by bcopeland** [comment]
Ok dropped this one, merged the other.  Thanks!

**Pull request closed without merging**
