### PR TITLE
Fix invalid accesses

### PR DESCRIPTION
**Pull request by fhuberts**
Disclaimer: only compile-tested

### CODE REVIEW

**Comment by bcopeland** [comment]
Thanks - this looks reasonable.  I think I would prefer if the send_nlmsg() and friends just never freed the message and pushed that responsibility to the caller, although I haven't done the diff to see how that looks compared to this.  Anyway when I get some free time I'll merge this or an edited version that does the latter on top.

**Comment by fhuberts** [comment]
It's a bit mixed, some sites use free, others don't.
The ones that do basically do so (only) because of debugging code.

Which is why I decided to do it this way.

**Comment by fhuberts** [comment]
The ones that do ==> The ones that don't

**Comment by bcopeland** [comment]
On Wed, Jan 06, 2016 at 06:31:03AM -0800, Ferry Huberts wrote:
> The ones that do ==> The ones that don't

Yep, I understand why you did it that way, I think it's just confusing
that the function freed msg in the first place - it leads to some weird
looking error paths even in the ones that don't have debug messages.

So, doing it everywhere would probably be a net positive.

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by alexgrin** [comment]
I agree with Bob, making it a uniform requirement to free will likely reduce confusion.

**Comment by fhuberts** [comment]
I'll put a commit on top to do that

**Comment by fhuberts** [comment]
I decided to squash all the commits together in this update because that makes the patch much more readable with the explicit free calls

**Comment by fhuberts** [comment]
thanks

**Pull request merged**
