### PR TITLE
Rekey

### PR DESCRIPTION
**Pull request by fhuberts**
meshd-nl80211: add re-key support
    
    Re-key checks that the peer-to-peer link encryption keys have been
    programmed correctly on both sides of the link.
    
    This is needed for chips/drivers that have problems with new peer-to-peer
    link encryption keys being programmed. Especially ath9k is relevant
    since it has exactly this problem when it's under load.
    
    When a peer node has been authenticated (the peer-to-peer link encryption
    keys have been programmed), then the re-key process is started:
    - An UDP packet containing the peer's MAC address, the node's MAC address,
      IP address and UDP reply port is sent to a multicast address.
    - This UDP packet is received by all neighbours and only the peer node
      with the same MAC address as the peer MAC address as in the UDP packet
      replies with an UDP packet to the IP address and UDP port combination
      as in the received UDP packet.
    - The node that started the re-key process receives that UDP packet and
      conclude that the peer-to-peer link encryption keys have been installed
      correctly.
    
    The sending of the UDP packets to the multicast address is retried a few
    times when no reply is received from the correct node within a certain
    timeout.
    
    When the maximum number of retries has been exceeded then the node
    concludes that the peer-to-peer link encryption keys have not been
    installed correctly and therefore restarts the authentication process
    for the peer.
    
    When the node has concluded that the peer-to-peer link encryption keys
    have been installed correctly, but it's still receiving UDP packets on
    the multicast address from the corresponding peer node, then the other
    side of the link has not installed the peer-to-peer link encryption keys
    correctly and the node therefore restarts the authentication process for
    the peer.
    
    This patch was originally written by Alexis Green and then further
    adjusted by me.
    
    Originally-by: Alexis Green <agreen@cococorp.com>
    Signed-off-by: Ferry Huberts <ferry.huberts@pelagic.nl>

### CODE REVIEW

**Comment by fhuberts** [comment]
figuring out a bad interaction between olsrd and authsae right now, hold off with merging please.

**Comment by fhuberts** [comment]
Ok, I've updated the PR with a few extra commits that explain and fix the issue I had.

Please consider for pulling in

**Comment by fhuberts** [comment]
Note: I have not changed the first 2 commits, so if you had reviewed those already then you can skip those. I just added 4 new commits

**Comment by fhuberts** [comment]
Cc: @bcopeland @alexgrin

**Comment by alexgrin** [comment]
Looks like good cleanup of my patch. How much testing have you done with this?

**Comment by fhuberts** [comment]
Very extensively.

I tested on a 2 node setup of our production mesh routers, under extreme wlan load conditions, using iperf as described in the 2nd commit.
I used a 2 node setup because that is enough to reproduce the problem

Our production mesh routers have a boatload of tricky (policy) routing, firewalling, and dynamic behaviour
I used our production mesh routers to verify that my patch can handle all the dynamics, and promptly found an issue with that. That issue is (mainly) fixed with the 6th commit (see its comments).

**Comment by fhuberts** [comment]
As a side note:
I was working with @MichelStam on an ath9k kernel patch to fix rekeying. Through an abundance of weird chip behaviour and lack of documentation I decided to first try to fix authsae for the issue, since fixing it was more important to me than the location of the fix.
Since I now have it working in authsae, we can evaluate and see if we still want to fix it in the kernel.

Maybe we want to lobby for having this fix (or an adjusted version of it) included in wpa_supplicant?

**Comment by bcopeland** [comment]
On Tue, Nov 29, 2016 at 11:48:10AM -0800, Ferry Huberts wrote:
> Maybe we want to lobby for having this fix (or an adjusted version of it) included in wpa_supplicant?

Good news, wpa_supplicant doesn't rekey sae! :)

Actually I think we should be doing MTK rekeys periodically instead of
rekeying SAE but wpa_s is not doing this either.  However, the spec seems to
be broken here because there isn't enough information in the exchanged frames
to reliably rekey the GTK.

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by alexgrin** [comment]
I still think that this is a bit of hack since it relies on having IPv4 addresses in the same subnet. It's probably fine to include it since it's off by default, but at some point it should be converted to use L2 frames - that way we wouldn't even need to worry about watching for IP address changes.

**Comment by fhuberts** [comment]
We can consider whether to rework it to use raw sockets and send plain ethernet frames, alike arp. then we don't need IP at all.
To me, that would be a follow-up though. I'd like this to go in first :-)

**Comment by fhuberts** [comment]
Some extra info:
Our routers have ath9k chips.
These chips have start having problems programming the keys when they are loaded with about 266KB/sec of traffic. Below that there is no problem, above that problems get more noticable proportionally with the rate.

**Comment by MichelStam** [comment]
Good work Ferry.

Here's a thought for the Ethernet version:
[https://en.wikipedia.org/wiki/IEEE_802.1ag]

> Loop-back (LB)
>    Loop-back messages otherwise known as MAC ping are Unicast frames that a MEP transmits,
> they are similar in concept to an Internet Control Message Protocol (ICMP) Echo (Ping) messages, 
> sending Loopback to successive MIPs can determine the location of a fault. Sending a high volume > of Loopback Messages can test bandwidth, reliability, or jitter of a service, which is similar to flood
> ping. A MEP can send a Loopback to any MEP or MIP in the service. Unlike CCMs, Loop back 
> messages are administratively initiated and stopped. 

That will at least break no other traffic. It is, however, a bit of work to implement.

**Comment by fhuberts** [comment]
please hold off merging.
we encountered some issues in our large test setup, using lots of vlans etc.

**Comment by fhuberts** [comment]
the issues are with ath5k systems, and _possibly_ unrelated to rekeying.
it will be next year until I have time to investigate.

**Comment by fhuberts** [comment]
I found the ath5k issue: nothing to do with rekey.
My sae config had 'htmode=HT20' which makes ath5k barf.

Re-opening

**Comment by fhuberts** [comment]
Alas, we found a problem again.
Will send a new PR once we have it fixed.
Sorry

**Pull request closed without merging**
