### PR TITLE
Upgraded for FreeBSD 11.0-CURRENT, but with one issue left.

### PR DESCRIPTION
**Pull request by fbettag**
Now this compiles nicely on FreeBSD 11.0. Thanks to Adrian Chadd's information which he provided me with, the only few things remaining on the FreeBSD Kernel side are the lines in my updated patch. They compile fine against current Head Kernel.

There is only one issue left, which is in ampe.h, which was wisely marked with "meh" by you guys. https://github.com/cozybit/authsae/blob/master/ampe.h#L7

```
clang -g -Wall -Werror  -I/usr/local/include -I.. -c meshd.c -o meshd.o
clang -g -Wall -Werror  -I/usr/local/include -I.. -c ../sae.c -o ../sae.o
In file included from ../sae.c:68:
In file included from ../ampe.h:8:
../linux/nl80211-copy.h:28:10: fatal error: 'linux/types.h' file not found
#include <linux/types.h>
         ^
1 error generated.
*** Error code 1

Stop.
make: stopped in /root/authsae/freebsd
zsh: exit 1     make
```

If i change it to < sys/types.h >, i get the following:

```
clang -g -Wall -Werror  -I/usr/local/include -I.. -c meshd.c -o meshd.o
clang -g -Wall -Werror  -I/usr/local/include -I.. -c ../sae.c -o ../sae.o
In file included from ../sae.c:68:
../ampe.h:56:31: error: field has incomplete type 'enum nl80211_channel_type'
    enum nl80211_channel_type channel_type;     /* HT mode */
                              ^
../ampe.h:56:10: note: forward declaration of 'enum nl80211_channel_type'
    enum nl80211_channel_type channel_type;     /* HT mode */
         ^
../ampe.h:78:31: error: field has incomplete type 'enum nl80211_channel_type'
    enum nl80211_channel_type channel_type;     /* HT mode */
                              ^
../ampe.h:56:10: note: forward declaration of 'enum nl80211_channel_type'
    enum nl80211_channel_type channel_type;     /* HT mode */
         ^
../sae.c:2198:29: error: declaration of 'struct config_setting_t' will not be visible outside of this function [-Werror,-Wvisibility]
sae_parse_libconfig (struct config_setting_t *sae_section, struct sae_config* config)
                            ^
../sae.c:2204:5: error: implicit declaration of function 'config_setting_lookup_int' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    config_setting_lookup_int(sae_section, "debug", (config_int_t *)&config->debug);
    ^
../sae.c:2205:15: error: implicit declaration of function 'config_setting_get_member' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    setting = config_setting_get_member(sae_section, "group");
              ^
../sae.c:2205:13: error: incompatible integer to pointer conversion assigning to 'struct config_setting_t *' from 'int' [-Werror,-Wint-conversion]
    setting = config_setting_get_member(sae_section, "group");
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sae.c:2208:21: error: implicit declaration of function 'config_setting_get_elem' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            group = config_setting_get_elem(setting, config->num_groups);
                    ^
../sae.c:2208:21: note: did you mean 'config_setting_get_member'?
../sae.c:2205:15: note: 'config_setting_get_member' declared here
    setting = config_setting_get_member(sae_section, "group");
              ^
../sae.c:2208:19: error: incompatible integer to pointer conversion assigning to 'struct config_setting_t *' from 'int' [-Werror,-Wint-conversion]
            group = config_setting_get_elem(setting, config->num_groups);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sae.c:2212:17: error: implicit declaration of function 'config_setting_get_int_elem' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                config_setting_get_int_elem(setting, config->num_groups);
                ^
../sae.c:2212:17: note: did you mean 'config_setting_get_elem'?
../sae.c:2208:21: note: 'config_setting_get_elem' declared here
            group = config_setting_get_elem(setting, config->num_groups);
                    ^
../sae.c:2218:9: error: implicit declaration of function 'config_setting_lookup_string' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (config_setting_lookup_string(sae_section, "password", (const char **)&pwd)) {
        ^
../sae.c:2218:9: note: did you mean 'config_setting_lookup_int'?
../sae.c:2204:5: note: 'config_setting_lookup_int' declared here
    config_setting_lookup_int(sae_section, "debug", (config_int_t *)&config->debug);
    ^
10 errors generated.
*** Error code 1

Stop.
make: stopped in /root/authsae-master/freebsd
zsh: exit 1     make
```

### CODE REVIEW

**Comment by bcopeland** [comment]
Yes, I suppose to be cross-platform again ampe.h would need to define its own enum for HT operation instead of using the one from linux/types, and translate between them.

**Comment by fbettag** [comment]
The FreeBSD community would probably very much appreciate it ;)

**Comment by bcopeland** [comment]
So I had a look at this -- it's all in the BSD code so I don't feel too strongly, but why change all the strlcpy()s to snprintf?  I was under the impression that bsd had strlcpy...

There is also some whitespace damage - e.g. 
```
-            strlcpy(ireq.i_name, inf->ifname, IFNAMSIZ);
+               snprintf(ireq.i_name, sizeof(ireq.i_name), "%s", inf->ifname);
```
There's a tab / space change in that line and some others.

**Comment by bcopeland** [comment]
I went ahead and fixed the SAE thing.  Let me know if you want to respin the freebsd PR per my above comments or just want to take it as-is.

**Comment by fbettag** [comment]
Thanks! I'll give it another try and fix the indenting right with it.

**Comment by bcopeland** [comment]
No, no issues with snprintf from a correctness standpoint, I just didn't see the reason.  Thanks for letting me know.

**Comment by fbettag** [comment]
So i've cleaned up the indenting and one minor define that's missing on FreeBSD.

libsae.a builds fine now.
screen shot 2016-03-17 at 12 30 43

The only issues remaining are these, not sure yet, but will dig deeper once there is more time:
```
# make 
clang -o meshd meshd.o ../common.o ../sae.o ../service.o -L/usr/lib -L/usr/local/lib -L../build -lcrypto -lsae -lconfig
meshd.o: In function `main':
/authsae-orig/freebsd/meshd.c:836: undefined reference to `sae_read_config'
../sae.o: In function `create_candidate':
/authsae-orig/freebsd/../sae.c:1354: undefined reference to `peer_created'
../build/libsae.a(ampe.c.o): In function `set_link_state':
/authsae-orig/ampe.c:107: undefined reference to `set_plink_state'
../build/libsae.a(ampe.c.o): In function `fsm_step':
/authsae-orig/ampe.c:748: undefined reference to `estab_peer_link'
/authsae-orig/ampe.c:780: undefined reference to `estab_peer_link'
/authsae-orig/ampe.c:844: undefined reference to `meshd_set_mesh_conf'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make: stopped in /authsae-orig/freebsd
zsh: exit 1     make
```

**Comment by fbettag** [comment]
I also have no idea why github doesn't somehow pick up on your ampe.h changes as they are missing from my repo. No idea how that works. If you want, i can just upload a unified diff for it.

**Comment by bcopeland** [comment]
Is more work being done on this?  I'm going to close it for now, feel free to resend a pull if there's a clean diff for it.

**Pull request closed without merging**
